import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: '토스 (Toss)',
      position: 'Commerce Log Automation팀, Server Developer',
      startedAt: '2025-08',
      descriptions: [
        '사내 앱 로그 검증 자동화 서버 애플리케이션 개발 및 운영 담당',
        'Kotlin/Spring Boot 기반 API 서버 및 MySQL 데이터 모델 설계',
        '실물 기기 자동화 시스템(네뷸라) 및 로그 파이프라인 연동 개발',
        'Flowise 기반 LLM 연동 개발 및 검증 자동화 기능 확장',
      ],
      skillKeywords: [
        'Kotlin',
        'Spring Boot',
        'MySQL',
        'Redis',
        'Kafka',
        'ElasticSearch',
        'Kibana',
        'LLM',
        'Flowise',
      ],
    },
    {
      title: '현대오토에버 (Hyundai Autoever)',
      position: '차량제어서비스개발팀, Backend Developer',
      startedAt: '2025-01',
      endedAt: '2025-07',
      descriptions: [
        '디지털키 1, 2 내수 시스템 개발 및 서버 관리',
        'Kubernetes, AWS 포함한 인프라 작업',
        'DB 쿼리 분석 및 index, 프로시저 설정',
        '레거시 개선 및 유지보수 작업',
      ],
      skillKeywords: [
        'Java',
        'Spring Boot',
        'PostgreSQL',
        'Kafka',
        'Tomcat',
        'Jenkins',
        'Grafana',
        'OpenSearch',
        'PinPoint',
      ],
    },
    {
      title: '지마켓(Gmarket)',
      position: 'Web Frontend팀, Web Service Developer',
      startedAt: '2022-05',
      endedAt: '2024-12',
      descriptions: [
        'Kotlin/Spring Boot 기반 API 서버 설계 및 개발',
        'Openshift(Red Hat Kubernetes)을 이용한 컨테이너 오케스트레이션',
        '이벤트 플랫폼, 기획전 등 대규모 트래픽 처리 도메인 담당',
        '레거시 개선 및 유지보수 작업',
        'Datadog 모니터링 시스템 연동, 대시보드 생성 및 Alert 체계 구축',
      ],
      skillKeywords: [
        'Kotlin',
        'Spring Boot',
        'Oracle',
        'SQL-Server',
        'Node.js',
        'Express.js',
        'Redis',
        'MongoDB',
        'Jenkins',
        'C#',
        '.NET',
        'Prometheus',
        'Grafana',
        'Kibana',
        'Datadog',
        'Armeria',
        'gRPC',
      ],
    },
    {
      title: '아이엠비씨스템(IMB System)',
      position: '기업부설연구소, 연구원',
      startedAt: '2019-06',
      endedAt: '2022-05',
      descriptions: [
        '다양한 SI 프로젝트 참여 및 개발 수주',
        'Spring Framework 기반 자체 솔루션 고도화',
        'DB 설계 및 쿼리 작성',
        'Linux 서버 세팅 및 모니터링',
        '개발 공수 산정, 일정 관리 매니징',
      ],
      skillKeywords: [
        'Java',
        'Spring Framework',
        'Android',
        'Javascript',
        'Oracle',
        'PostgreSQL',
        'Wildfly',
        'Linux',
        'VM Ware',
        'xFrame',
      ],
    },
  ],
};

export default experience;
