import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: '비바리퍼블리카 (Viva Republica)',
      position: 'Ads Log Automation팀, Server Developer (PO 겸임)',
      startedAt: '2026-07',
      descriptions: [
        '2026.07 커머스 로그 자동화팀에서 광고(Ads) 조직으로 전배, 팀 리드·서버·광고 전환 검수 PO 겸임',
        '앱 로그 검증 자동화 플랫폼(탈칵) 운영은 계속 맡으며, 광고 전환 로그 검수 자동화 플랫폼을 신규로 설계·구축',
        '검수자가 기기 미러링으로 광고 퍼널을 수행하고(Human-in-the-Loop), 추적키로 전환 로그를 격리해 자동 판정하는 구조 설계',
        '광고 프로덕트·데이터·캠페인·기기 자동화 팀과 판정 기준 수립 및 협업, 신규 PO·서버 개발자 온보딩 체계 설계',
      ],
      skillKeywords: [
        'Kotlin',
        'Spring Boot',
        'MySQL',
        'Redis',
        'Kafka',
        'ElasticSearch',
        'Kibana',
        'LLM',
        'Flowise',
        'MCP',
      ],
    },
    {
      title: '비바리퍼블리카 (Viva Republica)',
      position: 'Commerce Log Automation팀, Server Developer',
      startedAt: '2025-08',
      endedAt: '2026-06',
      descriptions: [
        '토스 코어 내 커머스 도메인 소속으로 앱 로그 검증 자동화 플랫폼을 PoC부터 라이브까지 구축',
        '서버 개발 전담, Kotlin/Spring Boot 기반 API 서버 및 MySQL 데이터 모델 설계',
        '실물 기기 자동화 시스템 및 로그 파이프라인 연동, 통합 어드민 → 전용 어드민 → 캔버스(DAG) 기반 시나리오 설계로 제품 고도화',
        'LLM(Flowise) 기반 AI 정답지 자동 생성, 캔버스 오토매핑, MCP 서버 내장, Kafka 기반 비동기 실행 구조 개발',
        '앱 로그를 넘어 결제·인증 등 서버 도메인 로그까지 검증 대상 확장, 관련 특허 2건 출원',
        '2026.05~ 팀 내 기획(PO) 역할 병행 시작',
      ],
      skillKeywords: [
        'Kotlin',
        'Spring Boot',
        'MySQL',
        'Redis',
        'Kafka',
        'ElasticSearch',
        'Kibana',
        'LLM',
        'Flowise',
      ],
    },
    {
      title: '현대오토에버 (Hyundai Autoever)',
      position: '차량제어서비스개발팀, Backend Developer',
      startedAt: '2025-01',
      endedAt: '2025-07',
      descriptions: [
        '디지털키 1, 2 내수 시스템 개발 및 서버 관리',
        'Kubernetes, AWS 포함한 인프라 작업',
        'DB 쿼리 분석 및 index, 프로시저 설정',
        '레거시 개선 및 유지보수 작업',
      ],
      skillKeywords: [
        'Java',
        'Spring Boot',
        'PostgreSQL',
        'Kafka',
        'Tomcat',
        'Jenkins',
        'Grafana',
        'OpenSearch',
        'PinPoint',
      ],
    },
    {
      title: '지마켓(Gmarket)',
      position: 'Web Frontend팀, Web Service Developer',
      startedAt: '2022-05',
      endedAt: '2024-12',
      descriptions: [
        'Kotlin/Spring Boot 기반 API 서버 설계 및 개발',
        'Openshift(Red Hat Kubernetes)을 이용한 컨테이너 오케스트레이션',
        '이벤트 플랫폼, 기획전 등 대규모 트래픽 처리 도메인 담당',
        '레거시 개선 및 유지보수 작업',
        'Datadog 모니터링 시스템 연동, 대시보드 생성 및 Alert 체계 구축',
      ],
      skillKeywords: [
        'Kotlin',
        'Spring Boot',
        'Oracle',
        'SQL-Server',
        'Node.js',
        'Express.js',
        'Redis',
        'MongoDB',
        'Jenkins',
        'C#',
        '.NET',
        'Prometheus',
        'Grafana',
        'Kibana',
        'Datadog',
        'Armeria',
        'gRPC',
      ],
    },
    {
      title: '아이엠비씨스템(IMB System)',
      position: '기업부설연구소, 연구원',
      startedAt: '2019-06',
      endedAt: '2022-05',
      descriptions: [
        '다양한 SI 프로젝트 참여 및 개발 수주',
        'Spring Framework 기반 자체 솔루션 고도화',
        'DB 설계 및 쿼리 작성',
        'Linux 서버 세팅 및 모니터링',
        '개발 공수 산정, 일정 관리 매니징',
      ],
      skillKeywords: [
        'Java',
        'Spring Framework',
        'Android',
        'Javascript',
        'Oracle',
        'PostgreSQL',
        'Wildfly',
        'Linux',
        'VM Ware',
        'xFrame',
      ],
    },
  ],
};

export default experience;
